version: "3.8"

services:
  db:
    image: postgres
    container_name: postgresql_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SUPERUSER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DBNAME}
  
volumes: 
  pgdata:

